import pandas

df = pandas.read_csv("data/produtos.csv")

df['marca'] = df['marca'].replace('Hashtag', '3 coracoes')
df['marca'] = df['marca'].replace('Sony', '3 coracoes')
df['marca'] = df['marca'].replace('Logitech', 'Santa Clara')
df['marca'] = df['marca'].replace('Multilaser', 'Cafe brasileiro')
df['marca'] = df['marca'].replace('LG', 'tres')
df['marca'] = df['marca'].replace('Samsung', '.br')
df['marca'] = df['marca'].replace('Philco', '.br Gold')
df['marca'] = df['marca'].replace('Xiaomi', 'Pimpinela')
df['marca'] = df['marca'].replace('Apple', '3 coracoes')
df['marca'] = df['marca'].replace('TCL', 'Kimimo')
df['marca'] = df['marca'].replace('SEMP', 'Cafe Fino Grao')
df['marca'] = df['marca'].replace('HP', 'Leticia')
df['marca'] = df['marca'].replace('Asus', 'Cafe Fort')
df['marca'] = df['marca'].replace('Motorola', 'Cafe Itamaraty')
df['marca'] = df['marca'].replace('Toshiba', 'Cruzeiro')
df['marca'] = df['marca'].replace('Dell', 'Amigo')
df['marca'] = df['marca'].replace('Lenovo', 'Cafe Cirol')
df['marca'] = df['marca'].replace('Acer', 'Cafe 3 fazendas')
df['marca'] = df['marca'].replace('Microsoft', 'Bandeira')
df['marca'] = df['marca'].replace('Nikon', 'Bandeira')

df['tipo'] = df['tipo'].replace('Mouse', 'Cafe Soluvel')
df['tipo'] = df['tipo'].replace('Camera', 'Cafe Soluvel')
df['tipo'] = df['tipo'].replace('Camisa', 'Cafe em graos')
df['tipo'] = df['tipo'].replace('Acessorios', 'Capsulas de cafe')
df['tipo'] = df['tipo'].replace('Celular', 'Cafe moído')
df['tipo'] = df['tipo'].replace('Fone', 'Cafe descafeinado')
df['tipo'] = df['tipo'].replace('Bone', 'Xaropes de sabores para cafe')
df['tipo'] = df['tipo'].replace('Televisao', 'Cafe gourmet')
df['tipo'] = df['tipo'].replace('Relogio', 'Cafe especial')
df['tipo'] = df['tipo'].replace('Notebook', 'Cafe aromatizado')
df['tipo'] = df['tipo'].replace('Teclado', 'Cafe gelado')
df['tipo'] = df['tipo'].replace('Mochila', 'Jarras para café gelado')
df['tipo'] = df['tipo'].replace('Teclado', 'Filtros de papel para cafe')
df['tipo'] = df['tipo'].replace('Casaco', 'Espumadores de leite')

df.to_csv("data/produtos3c.csv")
# print(df)
