import pandas

df = pandas.read_csv("data/produtos.csv")

df['marca'] = df['marca'].replace('Hashtag', '3 corações')
df['marca'] = df['marca'].replace('Sony', '3 corações')
df['marca'] = df['marca'].replace('Logitech', 'Santa Clara')
df['marca'] = df['marca'].replace('Multilaser', 'Café brasileiro')
df['marca'] = df['marca'].replace('LG', 'tres')
df['marca'] = df['marca'].replace('Samsung', '.br')
df['marca'] = df['marca'].replace('Philco', '.br Gold')
df['marca'] = df['marca'].replace('Xiaomi', 'Pimpinela')
df['marca'] = df['marca'].replace('Apple', 'Café iguaçu')
df['marca'] = df['marca'].replace('TCL', 'Kimimo')
df['marca'] = df['marca'].replace('SEMP', 'Café Fino Grão')
df['marca'] = df['marca'].replace('HP', 'Letícia')
df['marca'] = df['marca'].replace('Asus', 'Café Fort')
df['marca'] = df['marca'].replace('Motorola', 'Café Itamaraty')
df['marca'] = df['marca'].replace('Toshiba', 'Cruzeiro')
df['marca'] = df['marca'].replace('Dell', 'Amigo')
df['marca'] = df['marca'].replace('Lenovo', 'Café Cirol')
df['marca'] = df['marca'].replace('Acer', 'Café 3 fazendas')
df['marca'] = df['marca'].replace('Microsoft', 'Bandeira')
df['marca'] = df['marca'].replace('Nikon', 'Bandeira')

df['tipo'] = df['tipo'].replace('Mouse', 'Café Solúvel')
df['tipo'] = df['tipo'].replace('Camera', 'Café Solúvel')
df['tipo'] = df['tipo'].replace('Camisa', 'Café em grãos')
df['tipo'] = df['tipo'].replace('Acessorios', 'Cápsulas de café')
df['tipo'] = df['tipo'].replace('Celular', 'Café moído')
df['tipo'] = df['tipo'].replace('Fone', 'Café descafeinado')
df['tipo'] = df['tipo'].replace('Bone', 'Xaropes de sabores para café')
df['tipo'] = df['tipo'].replace('Televisao', 'Café gourmet')
df['tipo'] = df['tipo'].replace('Relogio', 'Café especial')
df['tipo'] = df['tipo'].replace('Notebook', 'Café aromatizado')
df['tipo'] = df['tipo'].replace('Teclado', 'Café gelado')
df['tipo'] = df['tipo'].replace('Mochila', 'Jarras para café gelado')
df['tipo'] = df['tipo'].replace('Teclado', 'Filtros de papel para café')
df['tipo'] = df['tipo'].replace('Casaco', 'Espumadores de leite')

# df.to_csv("data/produtos3c.csv")
# print(df)
